apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: demo-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
# this line is an optional. We can use a domain instead of IP address with editing /etc/hosts as well.
#  - host: hello-vilag.info
  - http:
      paths:
      - path: /demo
        backend:
          serviceName: apache2
          servicePort: 80
