######## Preparing:
# kubectl create secret generic user-pass --from-literal=username=test --from-literal=password=secret

#After I created the secret (user-pass) above, the system used base64 encoding algorithm to store it in encrypted form.
#No, we can not feel in safe as it can be decrypted using a very simple bash command. But it is good enough if we
#do not want to store any sensitive data in raw format rather than using encryption at all. I could have used kuber-
#netes access management, and restrict who can access the information stored in the cluster, but that is a lesson later.

#There are 3 different types of secret: docker-registry, tls and generic. According to the secret's purpose, it is
#useable for a secure http protocol via https, making a docker private repository connection and for login authenti-
#cation to an app. In case, I used for the last method. It is not far more secured, but it can give a bit more safe-
#ty. My aim was to demonstrate these two type of solutions: configMap (example-cm.yml) and secret.
#Using the secret object, it can be more secured with using some extra stuffs and feature, but portability and
#immutability was the most important facts to me in this time.
########

apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: jenkins
spec:
  rules:
  - http:
      paths:
      - path: /jenkins
        backend:
          serviceName: jenkins
          servicePort: 8080

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins
spec:
  selector:
    matchLabels:
      type: app
      service: jenkins
  template:
    metadata:
      labels:
        type: app
        service: jenkins
    spec:
      containers:
      - name: jenkins
        image: vfarcic/jenkins
        env:
        - name: JENKINS_OPTS
          value: --prefix=/jenkins
        - name: SECRETS_DIR
          value: /etc/secrets
        volumeMounts:
        - name: jenkins-auth
          mountPath: /etc/secrets
      volumes:
      - name: jenkins-auth
        secret:
          secretName: user-pass
          defaultMode: 0444
          items:
          - key: username
            path: jenkins-user
          - key: password
            path: jenkins-pass

---

apiVersion: v1
kind: Service
metadata:
  name: jenkins
spec:
  ports:
  - port: 8080
  selector:
    type: app
    service: jenkins

